version: "3.9"

services:
  mysql:
    image: mysql:8.4
    container_name: mysql-plataforma
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: plataforma_ideias
      MYSQL_USER: grupo4
      MYSQL_PASSWORD: 123456

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: