spring.datasource.url=jdbc:mysql://localhost:3306/plataforma_ideias
spring.datasource.username=grupo4
spring.datasource.password=123456

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

logging.level.org.springframework.security=DEBUG

api.security.token.secret=${JWT_SECRET:minha-chave-secreta-super-segura-e-longa-12345}